spring:
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://localhost:3306/spring_news?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 196610121
      login-timeout: 30000
      max-active: 20
      default-auto-commit: true
      max-wait: 30000
      min-idle: 5
      filters: stat
      initialSize: 2
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 200
  redis:
    port: 6379
    database: 1
    password: 196610121
    host: localhost
mybatis-plus:
  type-aliases-package: top.krasus1966.news.entity
  mapper-locations: classpath:mapper/*.xml

website:
  domain-name: localhost
